In [51]:
import numpy as np

In [52]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

Creating an Array : 

In [53]:
l=[1,4,6,8]
l

[1, 4, 6, 8]

In [54]:
arr=np.array(l)
arr

array([1, 4, 6, 8])

In [55]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [58]:
a3=np.ones(5)
a3

array([1., 1., 1., 1., 1.])

In [59]:
a4=np.eye(3)
a4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
ar1=np.zeros((3,3))
ar1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [61]:
ar2=np.ones((3,3))
ar2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [62]:
ar3=np.arange(10)
ar3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
ar4=np.arange(1,11)
ar4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
ar5=np.arange(1,11,2)
ar5

array([1, 3, 5, 7, 9])

In [65]:
ar6=np.linspace(1,10,5)
ar6

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [66]:
arr7=np.full(5,3)
arr7

array([3, 3, 3, 3, 3])

In [67]:
arr8=np.full((3,3),8)
arr8

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [68]:
r1=np.random.rand(3,3)
r1

array([[0.79670968, 0.01958211, 0.58670951],
       [0.15166456, 0.36970442, 0.06775735],
       [0.1273856 , 0.16720638, 0.50201443]])

In [69]:
r2=np.random.rand(5)
r2

array([0.048532  , 0.31442028, 0.22319653, 0.97143638, 0.40463145])

In [70]:
r3=np.random.randint(5)
r3

3

In [71]:
r4=np.random.randint(3,10)
r4

9

In [72]:
r5=np.random.randint(3,10,5)
r5

array([7, 7, 6, 6, 7], dtype=int32)

In [73]:
r6=np.random.randint(3,10,(3,3))
r6

array([[5, 4, 6],
       [6, 6, 3],
       [6, 6, 7]], dtype=int32)

Indexing of Array : 

In [74]:
arr=np.array(l)
print(arr)

[1 4 6 8]


In [75]:
print(arr[0])

1


In [76]:
(arr[3])

np.int64(8)

In [77]:
(arr[-3])

np.int64(4)

In [78]:
(arr[-1])

np.int64(8)

In [79]:
a2=np.random.randint(1,10,(3,3))
a2

array([[3, 5, 7],
       [7, 1, 2],
       [2, 4, 3]], dtype=int32)

In [80]:
(a2[0][1])

np.int32(5)

In [81]:
(a2[2][0])

np.int32(2)

In [82]:
(a2[0,1])

np.int32(5)

In [83]:
(a2[1,2])

np.int32(2)

In [84]:
print(a2)

[[3 5 7]
 [7 1 2]
 [2 4 3]]


Slicing on Array : 

In [85]:
a=np.arange(3,10)
a

array([3, 4, 5, 6, 7, 8, 9])

In [86]:
a[0:3]

array([3, 4, 5])

In [87]:
a[-1:-5:-1]

array([9, 8, 7, 6])

In [88]:
a[2:6]

array([5, 6, 7, 8])

In [89]:
a

array([3, 4, 5, 6, 7, 8, 9])

In [90]:
a[0:]

array([3, 4, 5, 6, 7, 8, 9])

In [91]:
a[0::1]

array([3, 4, 5, 6, 7, 8, 9])

In [92]:
a[0::2]

array([3, 5, 7, 9])

In [93]:
a[::]

array([3, 4, 5, 6, 7, 8, 9])

In [94]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3])

In [95]:
a2=np.random.randint(1,10,(3,3))
a2

array([[3, 6, 1],
       [2, 4, 1],
       [8, 2, 2]], dtype=int32)

In [96]:
a2[0:2,2]

array([1, 1], dtype=int32)

In [97]:
a2[0:,1]

array([6, 4, 2], dtype=int32)

In [98]:
a2[1,0:2]

array([2, 4], dtype=int32)

In [99]:
a2

array([[3, 6, 1],
       [2, 4, 1],
       [8, 2, 2]], dtype=int32)

In [100]:
a2[:,:]

array([[3, 6, 1],
       [2, 4, 1],
       [8, 2, 2]], dtype=int32)

In [101]:
a2[0:,1:]

array([[6, 1],
       [4, 1],
       [2, 2]], dtype=int32)

Shape , Size and Datatype of Array : 

In [102]:
a

array([3, 4, 5, 6, 7, 8, 9])

In [103]:
print(a.shape)

(7,)


In [104]:
a2

array([[3, 6, 1],
       [2, 4, 1],
       [8, 2, 2]], dtype=int32)

In [105]:
print(a2.shape)

(3, 3)


In [106]:
print(a.size)

7


In [107]:
print(a2.size)

9


In [108]:
print(a.dtype)

int64


In [109]:
print(a2.dtype)

int32


Mathematical Operations on Array : 

In [110]:
a1=np.arange(11,20)
a2=np.arange(21,30)

In [111]:
a1

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [112]:
a2

array([21, 22, 23, 24, 25, 26, 27, 28, 29])

In [113]:
a1+a2

array([32, 34, 36, 38, 40, 42, 44, 46, 48])

In [114]:
a1*a2

array([231, 264, 299, 336, 375, 416, 459, 504, 551])

In [115]:
a3=np.array([16,81,25,121,9])
np.sqrt(a3)

array([ 4.,  9.,  5., 11.,  3.])