In [1]:
import numpy as np

Mathematical Operations :

In [2]:
a1=np.array([1,2,4,5,6])
a1 

array([1, 2, 4, 5, 6])

In [3]:
a2=np.array([7,8,6,9,4])
a2

array([7, 8, 6, 9, 4])

In [4]:
a1+a2

array([ 8, 10, 10, 14, 10])

In [5]:
a1-a2

array([-6, -6, -2, -4,  2])

In [6]:
a1*a2

array([ 7, 16, 24, 45, 24])

In [7]:
a1/a2

array([0.14285714, 0.25      , 0.66666667, 0.55555556, 1.5       ])

In [8]:
ans=a1**a2
ans

array([      1,     256,    4096, 1953125,    1296])

In [9]:
np.sqrt(ans)

array([1.00000000e+00, 1.60000000e+01, 6.40000000e+01, 1.39754249e+03,
       3.60000000e+01])

In [10]:
a3=np.array([1.2,2.5,3.7,4.9])
a3

array([1.2, 2.5, 3.7, 4.9])

In [11]:
np.floor(a3)

array([1., 2., 3., 4.])

In [12]:
np.ceil(a3)

array([2., 3., 4., 5.])

In [13]:
np.round(a3)

array([1., 2., 4., 5.])

Combining Array : 

In [14]:
a1

array([1, 2, 4, 5, 6])

In [15]:
a2

array([7, 8, 6, 9, 4])

In [16]:
np.concatenate((a1,a2))

array([1, 2, 4, 5, 6, 7, 8, 6, 9, 4])

In [17]:
arr1=np.array([[3,5,7],[1,2,9],[4,6,8]])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [18]:
print(arr1)

[[3 5 7]
 [1 2 9]
 [4 6 8]]


In [19]:
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
np.vstack((arr1,arr2))

array([[3, 5, 7],
       [1, 2, 9],
       [4, 6, 8],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
np.hstack((arr1,arr2))

array([[3, 5, 7, 1, 2, 3],
       [1, 2, 9, 4, 5, 6],
       [4, 6, 8, 7, 8, 9]])

In [22]:
arr1.flatten()

array([3, 5, 7, 1, 2, 9, 4, 6, 8])

Splitting Array : 

In [23]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [24]:
np.split(arr,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [25]:
arr2=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [26]:
np.hsplit(arr2,3)

[array([[1, 2],
        [7, 8]]),
 array([[ 3,  4],
        [ 9, 10]]),
 array([[ 5,  6],
        [11, 12]])]

In [27]:
np.vsplit(arr2,2)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]

Searching in Array :

In [28]:
a1

array([1, 2, 4, 5, 6])

In [29]:
np.where(a1==7)

(array([], dtype=int64),)

In [30]:
a3=np.array([1,2,3,4,5,6,7,1])

In [31]:
np.where(a3==3)

(array([2]),)

In [32]:
np.where(a3>3)

(array([3, 4, 5, 6]),)

In [33]:
arr1

array([[3, 5, 7],
       [1, 2, 9],
       [4, 6, 8]])

In [34]:
np.where(arr1==5)

(array([0]), array([1]))

In [35]:
arr3=np.array([[1,2,3],[2,5,7],[4,5,2]])
arr3

array([[1, 2, 3],
       [2, 5, 7],
       [4, 5, 2]])

In [36]:
np.where(arr3==2)

(array([0, 1, 2]), array([1, 0, 2]))

Sorting of Array : 

In [37]:
a1

array([1, 2, 4, 5, 6])

In [38]:
np.sort(a1)

array([1, 2, 4, 5, 6])

In [39]:
#find how to sort in descending order.

In [40]:
arr3

array([[1, 2, 3],
       [2, 5, 7],
       [4, 5, 2]])

In [41]:
np.sort(arr3)

array([[1, 2, 3],
       [2, 5, 7],
       [2, 4, 5]])

In [42]:
#how find to sort in descending order.

In [43]:
#find how to sort col-wise & row-wise.

Aggregating & Statistical Functions :

In [44]:
a1

array([1, 2, 4, 5, 6])

In [45]:
np.sum(a1)

np.int64(18)

In [46]:
np.mean(a1)

np.float64(3.6)

In [47]:
np.median(a1)

np.float64(4.0)

In [48]:
np.max(a1)

np.int64(6)

In [49]:
np.min(a1)

np.int64(1)

In [50]:
np.std(a1)

np.float64(1.8547236990991407)

In [51]:
np.var(a1)

np.float64(3.44)

In [52]:
arr4=np.array([[1,2,3],[4,5,6]])

In [53]:
np.sum(arr4)

np.int64(21)

In [54]:
np.sum(arr4,axis=1)

array([ 6, 15])

In [55]:
np.sum(arr4,axis=0)

array([5, 7, 9])