Boolean Indexing (Filtering Array) :

In [96]:
import numpy as np

In [97]:
arr=np.array([10,15,20,25,30])
arr

array([10, 15, 20, 25, 30])

In [98]:
arr[True]

array([[10, 15, 20, 25, 30]])

In [99]:
arr[0]

np.int64(10)

In [100]:
arr[3]

np.int64(25)

In [101]:
l=[True,False,True,True,False]
l

[True, False, True, True, False]

In [102]:
arr[l]
#arr[[True,False,True,True,False]]

array([10, 20, 25])

In [103]:
arr

array([10, 15, 20, 25, 30])

In [104]:
l2=(arr%2==0)
l2

array([ True, False,  True, False,  True])

In [105]:
arr[l2]

array([10, 20, 30])

In [106]:
arr[arr%2==0]

array([10, 20, 30])

In [107]:
age=np.array([42,12,22,13,16])

In [108]:
age

array([42, 12, 22, 13, 16])

In [109]:
age[age>18]

array([42, 22])

In [110]:
age[age==22]

array([22])

In [111]:
a2=np.array([[3,5,7],[1,2,9],[6,4,2]])
a2

array([[3, 5, 7],
       [1, 2, 9],
       [6, 4, 2]])

In [112]:
l1=[True,False,True]

In [113]:
a2[l1]

array([[3, 5, 7],
       [6, 4, 2]])

Boolean Mask (Masking Array) : 

In [114]:
arr

array([10, 15, 20, 25, 30])

In [115]:
l

[True, False, True, True, False]

In [116]:
print(np.ma.array(arr,mask=l))

[-- 15 -- -- 30]


In [117]:
odd_numbers=np.ma.array(arr,mask=arr%2==0)
print(odd_numbers)

[-- 15 -- 25 --]


Reshaping Array : 

In [118]:
a2

array([[3, 5, 7],
       [1, 2, 9],
       [6, 4, 2]])

In [119]:
a2.flatten()        #Convert multi-dimensional array into 1-D array.

array([3, 5, 7, 1, 2, 9, 6, 4, 2])

In [120]:
a2.reshape(-1)      #Convert multi-dimensional array into 1-D array.

array([3, 5, 7, 1, 2, 9, 6, 4, 2])

In [121]:
a2.ravel()          #Convert multi-dimensional array into 1-D array.

array([3, 5, 7, 1, 2, 9, 6, 4, 2])

In [122]:
a1d=np.arange(0,12)
a1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [123]:
a1d.reshape(4,3)        #Converts 1-D array in to multi-dimensional array  e.g.,1D to 2D array.

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [124]:
a1d.reshape(2,-1)       #-1 means automatically decides the possible dimension .

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [125]:
a1d.reshape(-1,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [126]:
a1d.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [127]:
a1d.reshape(2,3,2)      # convert 1D array in to multi-dimensional array  e.g.,1D to 3D array.

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

Broadcasting of array :

Type of Broadcasting : 

In [128]:
arr

array([10, 15, 20, 25, 30])

In [129]:
#Scaler=>one element array
s1=[3]
s2=5
s3=np.array([6])

In [130]:
arr+s2

array([15, 20, 25, 30, 35])

In [131]:
arr+s1

array([13, 18, 23, 28, 33])

In [132]:
arr+8

array([18, 23, 28, 33, 38])

In [133]:
arr+s3

array([16, 21, 26, 31, 36])

2. Vector - Row vector 
          - Column Vector

=> Row Vector :

In [134]:
a1=np.array([[1,2,3],[4,5,6]])      #Shape (2,3)

In [135]:
a2=np.array([10,20,30])            #Shape(3,)

In [136]:
print(a1+a2)

[[11 22 33]
 [14 25 36]]


In [137]:
#a1.shape==(2,3)
#a2.shape==(3,)     =>broadcast to (2,3)        =>Addee to each row

=> column Vector :

In [138]:
a1=np.array([[1,2,3],[4,5,6]])

In [139]:
#a2=np.array([[10],[20]])
#a2
a2=np.array([10,20]).reshape(-1,1)

In [140]:
print(a1+a2)

[[11 12 13]
 [24 25 26]]


In [141]:
a2.shape=(2,1)      # => added down each row

3.Matrix Broadcasting

In [142]:
a1=np.array([[1],[2]])
a2=np.array([[10,20,30]])

In [143]:
print(a1)
print()
print(a2)
print()

[[1]
 [2]]

[[10 20 30]]



In [144]:
a3=a1+a2

In [145]:
print(a3)

[[11 21 31]
 [12 22 32]]


In [146]:
#a1 => (2,1) => expended across column.
#a2 => (1,3) => expended across rows.
#Result shape => (2,3)